"""Notification repository, provider, and transaction protocols."""
from __future__ import annotations
from dataclasses import dataclass
from typing import Protocol, Any
from packages.contracts import DeadLetterRecord, DeliveryAttempt, Notification, NotificationPreference, NotificationTemplate, TemplateVersion

@dataclass(frozen=True)
class NotificationPage:
    items: tuple[Notification,...]
    next_cursor: str|None

@dataclass(frozen=True)
class ProviderAcceptance:
    accepted: bool
    retryable: bool
    provider_reference: str|None
    reason_code: str|None

class NotificationProvider(Protocol):
    def deliver(self, notification:Notification, template:TemplateVersion, delivery_key:str)->ProviderAcceptance: ...

class WebhookDestinationAllowlist(Protocol):
    def permits(self, tenant_id:str, destination_reference:str)->bool: ...

class TemplateRepository(Protocol):
    def create(self,value:NotificationTemplate)->NotificationTemplate: ...
    def get(self,template_id:str)->NotificationTemplate|None: ...
    def update(self,value:NotificationTemplate,expected_version:int)->NotificationTemplate: ...
    def append_version(self,value:TemplateVersion)->TemplateVersion: ...
    def get_version(self,template_id:str,version_number:int)->TemplateVersion|None: ...
    def max_version(self,template_id:str)->int: ...

class NotificationRepository(Protocol):
    def create(self,value:Notification)->Notification: ...
    def get(self,notification_id:str)->Notification|None: ...
    def update(self,value:Notification,expected_version:int)->Notification: ...
    def list(self,tenant_id:str,limit:int,cursor:str|None)->NotificationPage: ...
    def get_by_dedup(self,tenant_id:str,deduplication_key:str)->Notification|None: ...

class AttemptRepository(Protocol):
    def append(self,value:DeliveryAttempt)->DeliveryAttempt: ...
    def list(self,notification_id:str)->tuple[DeliveryAttempt,...]: ...

class PreferenceRepository(Protocol):
    def put(self,value:NotificationPreference,expected_version:int|None)->NotificationPreference: ...
    def get(self,tenant_id:str,subject_reference:str,channel:str)->NotificationPreference|None: ...

class DeadLetterRepository(Protocol):
    def create(self,value:DeadLetterRecord)->DeadLetterRecord: ...
    def get(self,dead_letter_id:str)->DeadLetterRecord|None: ...

class NotificationUnitOfWork(Protocol):
    templates:TemplateRepository; notifications:NotificationRepository; attempts:AttemptRepository; preferences:PreferenceRepository; dead_letters:DeadLetterRepository; outbox:Any
    def __enter__(self)->"NotificationUnitOfWork": ...
    def __exit__(self,exc_type:object,exc_value:object,traceback:object)->None: ...
    def commit(self)->None: ...
class UnitOfWorkFactory(Protocol):
    def __call__(self)->NotificationUnitOfWork: ...
