"""Durable audit repositories and transaction contracts."""
from __future__ import annotations
from dataclasses import dataclass
from typing import Protocol,Any
from packages.contracts import AuditCheckpoint,AuditExportManifest,AuditRetentionPolicy,DurableAuditEvent
@dataclass(frozen=True)
class AuditPage:
    items:tuple[DurableAuditEvent,...]
    next_cursor:str|None
class AuditStreamRepository(Protocol):
    def next_sequence(self,tenant_id:str)->tuple[int,str]: ...
    def append(self,value:DurableAuditEvent)->DurableAuditEvent: ...
    def list(self,tenant_id:str,limit:int,cursor:str|None)->AuditPage: ...
    def range(self,tenant_id:str,first:int|None,last:int|None)->tuple[DurableAuditEvent,...]: ...
class CheckpointRepository(Protocol):
    def create(self,value:AuditCheckpoint)->AuditCheckpoint: ...
    def get(self,checkpoint_id:str)->AuditCheckpoint|None: ...
class ExportRepository(Protocol):
    def create(self,value:AuditExportManifest)->AuditExportManifest: ...
    def get(self,export_id:str)->AuditExportManifest|None: ...
class RetentionRepository(Protocol):
    def put(self,value:AuditRetentionPolicy,expected_version:int|None)->AuditRetentionPolicy: ...
    def get(self,tenant_id:str)->AuditRetentionPolicy|None: ...
class SourceEventRepository(Protocol):
    def get(self,event_id:str)->tuple[str,DurableAuditEvent]|None: ...
    def put(self,event_id:str,fingerprint:str,result:DurableAuditEvent)->None: ...
class AuditUnitOfWork(Protocol):
    stream:AuditStreamRepository; checkpoints:CheckpointRepository; exports:ExportRepository; retention:RetentionRepository; source_events:SourceEventRepository; outbox:Any
    def __enter__(self)->"AuditUnitOfWork": ...
    def __exit__(self,exc_type:object,exc_value:object,traceback:object)->None: ...
    def commit(self)->None: ...
class UnitOfWorkFactory(Protocol):
    def __call__(self)->AuditUnitOfWork: ...
