"""Provider-neutral storage metadata, blob, and transaction contracts."""

from __future__ import annotations
from dataclasses import dataclass
from typing import Protocol, Any
from packages.contracts import LegalHold, ObjectVersion, RetentionPolicy, StoredObject, UploadSession
from services.data_service_common import OutboxRecord

@dataclass(frozen=True)
class ObjectPage:
    items: tuple[StoredObject, ...]
    next_cursor: str | None

@dataclass(frozen=True)
class BlobMetadata:
    content_length: int
    algorithm: str
    digest: str

class BlobStore(Protocol):
    def stat(self, storage_key: str) -> BlobMetadata | None: ...

class ObjectRepository(Protocol):
    def create(self, value: StoredObject) -> StoredObject: ...
    def get(self, object_id: str) -> StoredObject | None: ...
    def update(self, value: StoredObject, expected_version: int) -> StoredObject: ...
    def list(self, tenant_id: str, limit: int, cursor: str | None) -> ObjectPage: ...

class ObjectVersionRepository(Protocol):
    def append(self, value: ObjectVersion) -> ObjectVersion: ...
    def get(self, object_version_id: str) -> ObjectVersion | None: ...
    def get_number(self, object_id: str, version_number: int) -> ObjectVersion | None: ...
    def replace_scan_status(self, value: ObjectVersion) -> ObjectVersion: ...

class UploadRepository(Protocol):
    def create(self, value: UploadSession) -> UploadSession: ...
    def get(self, upload_id: str) -> UploadSession | None: ...
    def update(self, value: UploadSession, expected_version: int) -> UploadSession: ...

class StoragePolicyRepository(Protocol):
    def put_retention(self, value: RetentionPolicy) -> RetentionPolicy: ...
    def get_retention(self, object_id: str) -> RetentionPolicy | None: ...
    def put_hold(self, value: LegalHold) -> LegalHold: ...
    def get_hold(self, object_id: str) -> LegalHold | None: ...

class StorageIdempotencyRepository(Protocol):
    def get(self, scope: tuple[str, str, str], key: str) -> tuple[str, Any] | None: ...
    def put(self, scope: tuple[str, str, str], key: str, fingerprint: str, result: Any) -> None: ...

class StorageUnitOfWork(Protocol):
    objects: ObjectRepository
    versions: ObjectVersionRepository
    uploads: UploadRepository
    policies: StoragePolicyRepository
    idempotency: StorageIdempotencyRepository
    outbox: Any
    def __enter__(self) -> "StorageUnitOfWork": ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
    def commit(self) -> None: ...

class UnitOfWorkFactory(Protocol):
    def __call__(self) -> StorageUnitOfWork: ...
