"""Analytics event, snapshot, idempotency, and transaction protocols."""
from __future__ import annotations
from typing import Protocol,Any
from packages.contracts import AnalyticsEvent,AnalyticsSnapshot
class AnalyticsEventRepository(Protocol):
    def append(self,value:AnalyticsEvent)->AnalyticsEvent: ...
    def get(self,event_id:str)->AnalyticsEvent|None: ...
    def range(self,tenant_id:str,start_at:str,end_at:str)->tuple[AnalyticsEvent,...]: ...
class SnapshotRepository(Protocol):
    def put(self,value:AnalyticsSnapshot)->AnalyticsSnapshot: ...
    def get(self,snapshot_id:str)->AnalyticsSnapshot|None: ...
class AnalyticsIdempotencyRepository(Protocol):
    def get(self,scope:tuple[str,str],key:str)->tuple[str,Any]|None: ...
    def put(self,scope:tuple[str,str],key:str,fingerprint:str,result:Any)->None: ...
class AnalyticsUnitOfWork(Protocol):
    events:AnalyticsEventRepository; snapshots:SnapshotRepository; idempotency:AnalyticsIdempotencyRepository; outbox:Any
    def __enter__(self)->"AnalyticsUnitOfWork": ...
    def __exit__(self,exc_type:object,exc_value:object,traceback:object)->None: ...
    def commit(self)->None: ...
class UnitOfWorkFactory(Protocol):
    def __call__(self)->AnalyticsUnitOfWork: ...
