"""Repository, exporter, and UnitOfWork protocols for platform operations."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol

from packages.contracts import (
    AlertOccurrence, AlertRule, DependencyHealth, Incident, IncidentTimelineEntry,
    MaintenanceWindow, MetricSample, OperationalHealthSnapshot, OperationalMetric,
    Runbook, RunbookExecution, RunbookStepResult, RunbookVersion, SLOEvaluation,
    ServiceIdentity, ServiceLevelIndicator, ServiceLevelObjective, TelemetryCheckpoint,
)


@dataclass(frozen=True)
class Page:
    items: tuple[Any, ...]
    next_cursor: str | None


@dataclass(frozen=True)
class OperationsIdempotencyRecord:
    operation: str
    tenant_id: str
    actor_subject: str
    key: str
    request_fingerprint: str
    original_result: Any


class MutableRepository(Protocol):
    def create(self, value: Any) -> Any: ...
    def get(self, key: str) -> Any | None: ...
    def update(self, value: Any, expected_version: int) -> Any: ...
    def list(self) -> tuple[Any, ...]: ...


class ImmutableRepository(Protocol):
    def append(self, value: Any) -> Any: ...
    def get(self, key: str) -> Any | None: ...
    def list(self) -> tuple[Any, ...]: ...


class ServiceIdentityRepository(MutableRepository, Protocol): ...
class MetricDefinitionRepository(MutableRepository, Protocol): ...
class MetricSampleRepository(ImmutableRepository, Protocol): ...
class DependencyHealthRepository(ImmutableRepository, Protocol): ...
class HealthSnapshotRepository(ImmutableRepository, Protocol): ...
class SLODefinitionRepository(MutableRepository, Protocol): ...
class SLOEvaluationRepository(ImmutableRepository, Protocol): ...
class AlertRuleRepository(MutableRepository, Protocol): ...
class AlertOccurrenceRepository(MutableRepository, Protocol): ...
class IncidentRepository(MutableRepository, Protocol): ...
class IncidentTimelineRepository(ImmutableRepository, Protocol): ...
class RunbookRepository(MutableRepository, Protocol): ...
class RunbookVersionRepository(ImmutableRepository, Protocol): ...
class RunbookExecutionRepository(MutableRepository, Protocol): ...
class RunbookStepResultRepository(ImmutableRepository, Protocol): ...
class MaintenanceWindowRepository(MutableRepository, Protocol): ...
class TelemetryCheckpointRepository(ImmutableRepository, Protocol): ...


class IdempotencyRepository(Protocol):
    def get(self, operation: str, tenant_id: str, actor_subject: str, key: str) -> OperationsIdempotencyRecord | None: ...
    def put(self, record: OperationsIdempotencyRecord) -> OperationsIdempotencyRecord: ...


class TelemetryExporter(Protocol):
    def export_sample(self, sample: MetricSample) -> None: ...
    def export_health(self, snapshot: OperationalHealthSnapshot) -> None: ...


class OperationsUnitOfWork(Protocol):
    service_identities: ServiceIdentityRepository
    metric_definitions: MetricDefinitionRepository
    metric_samples: MetricSampleRepository
    dependency_health: DependencyHealthRepository
    health_snapshots: HealthSnapshotRepository
    sli_definitions: MutableRepository
    slo_definitions: SLODefinitionRepository
    slo_evaluations: SLOEvaluationRepository
    alert_rules: AlertRuleRepository
    alert_occurrences: AlertOccurrenceRepository
    incidents: IncidentRepository
    incident_timeline: IncidentTimelineRepository
    runbooks: RunbookRepository
    runbook_versions: RunbookVersionRepository
    runbook_executions: RunbookExecutionRepository
    runbook_step_results: RunbookStepResultRepository
    maintenance_windows: MaintenanceWindowRepository
    telemetry_checkpoints: TelemetryCheckpointRepository
    idempotency: IdempotencyRepository
    outbox: object

    def __enter__(self) -> "OperationsUnitOfWork": ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class UnitOfWorkFactory(Protocol):
    def __call__(self) -> OperationsUnitOfWork: ...
